apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classifier
  template:
    metadata:
      labels:
        app: image-classifier
    spec:
      containers:
        - name: image-classifier
          image: diegohmeneses/image-classifier:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret